import type {AppState,Bridge} from './types';
import skins from '../shared/skins.json';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function daysUntil(date:string){const now=new Date();return Math.round((Date.parse(date+'T00:00:00Z')-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);}
const remaining=(date:string)=>{const days=daysUntil(date);return days===0?'就是今天':days>0?`还有 ${days} 天`:`已过 ${-days} 天`;};
export function applySkin(state:AppState){const s=skins.find(s=>s.id===(state.activation?.active?state.deskTools?.skin:'garden'))||skins[0];document.body.dataset.skin=s.id;document.documentElement.style.setProperty('--desk-surface',s.surface);document.documentElement.style.setProperty('--desk-ink',s.ink);document.documentElement.style.setProperty('--desk-accent',s.accent);}
export function renderDeskTools(el:Element,state:AppState,bridge:Bridge,changed:(s:AppState)=>void,toast:(s:string)=>void,board=false){
  if([...el.querySelectorAll('form')].some(form=>form.contains(document.activeElement)))return;
  const data=state.deskTools||{notes:[],countdowns:[],skin:'garden',visible:false},active=!!state.activation?.active;
  const notes=data.notes.filter(n=>!board||n.pinned),dates=data.countdowns.filter(n=>!board||n.pinned);
  el.innerHTML=`<div class="desk-tools-page">${board?`<header class="desk-board-header"><strong>栖候 · 今日小事</strong><button data-action="settings" aria-label="打开设置">管理</button><button data-desk-hide aria-label="隐藏小工具面板">×</button></header>`:`<div class="account-heading"><div><h2>给桌面，留一点生活</h2><p>便签与重要日子保存在本机，勾选“放在桌面”后显示在独立面板。</p></div><button class="subtle-button" data-desk-toggle ${!active?'disabled':''}>${data.visible?'隐藏':'显示'}桌面面板</button></div>`}
    ${!active&&!board?'<p class="tools-gate">便利贴、倒数日与场景皮肤由 Plus 解锁。已有内容仍可查看、复制、删除或导出备份。<button class="text-button" data-action="edition">查看激活方式 →</button></p>':''}
    <section class="desk-notes"><div class="section-heading"><h3>便利贴</h3><span>${data.notes.length}/8</span></div><div class="note-grid">${notes.map(n=>`<article class="desk-note" data-color="${esc(n.color)}"><h4>${esc(n.title)}</h4><p>${esc(n.text)||'空白便签'}</p>${!board?`<div><button class="text-button" data-edit-note="${esc(n.id)}" ${!active?'disabled':''}>编辑</button><button class="text-button" data-copy-note="${esc(n.id)}">复制</button><button class="text-button" data-remove-note="${esc(n.id)}">删除</button></div>`:''}</article>`).join('')||'<p class="hint">记一件想做的小事，或留一句给自己。</p>'}</div>
    ${!board?`<form id="note-form" class="desk-form"><input type="hidden" name="id"/><label>标题<input name="title" maxlength="40" required placeholder="今天的小事" ${!active?'disabled':''}/></label><label>内容<textarea name="text" maxlength="4000" rows="3" placeholder="随手记下，之后再做。" ${!active?'disabled':''}></textarea></label><div class="desk-form-row"><label>纸张<select name="color" ${!active?'disabled':''}><option value="cream">暖纸</option><option value="rose">淡粉</option><option value="blue">浅蓝</option></select></label><label class="desk-pin"><input name="pinned" type="checkbox" checked ${!active?'disabled':''}/>放在桌面</label><button class="primary-button" ${!active?'disabled':''}>保存便签</button><button class="text-button" type="reset">取消编辑</button></div></form>`:''}</section>
    <section class="desk-countdowns"><div class="section-heading"><h3>倒数日</h3><span>${data.countdowns.length}/8</span></div><div class="countdown-list">${dates.map(d=>`<article class="countdown-item"><div><strong>${esc(d.title)}</strong><span>${esc(d.date)}</span></div><b>${remaining(d.date)}</b>${!board?`<button class="text-button" data-edit-date="${esc(d.id)}" ${!active?'disabled':''}>编辑</button><button class="text-button" data-remove-date="${esc(d.id)}">删除</button>`:''}</article>`).join('')||'<p class="hint">把旅行、生日或项目完成的日子放在这里。</p>'}</div>
    ${!board?`<form id="date-form" class="desk-form"><input type="hidden" name="id"/><div class="desk-form-row"><label>事件<input name="title" maxlength="40" placeholder="下一次出发" required ${!active?'disabled':''}/></label><label>日期<input type="date" name="date" min="2000-01-01" max="2200-12-31" required ${!active?'disabled':''}/></label><label class="desk-pin"><input name="pinned" type="checkbox" checked ${!active?'disabled':''}/>放在桌面</label></div><div><button class="primary-button" ${!active?'disabled':''}>保存倒数日</button><button class="text-button" type="reset">取消编辑</button></div></form>`:''}</section>
    ${!board?`<section class="skin-gallery"><div class="section-heading"><h3>场景皮肤</h3><span>改变岛屿、植被与桌面卡片，保留建筑本色</span></div><div class="skin-options">${skins.map(s=>`<button data-skin-choice="${s.id}" aria-pressed="${s.id===(active?data.skin:'garden')}"><span class="skin-swatch" style="background:${s.surface};border-color:${s.accent}"><i style="background:#${s.grass.toString(16).padStart(6,'0')}"></i><i style="background:#${s.leaf.toString(16).padStart(6,'0')}"></i><i style="background:#${s.water.toString(16).padStart(6,'0')}"></i></span><strong>${s.name}</strong><small>${s.description}${s.id!=='garden'&&!active?' · Plus':''}</small></button>`).join('')}</div></section><button class="text-button" data-action="backup-tools">导出便签与倒数日备份 · JSON</button><p class="hint">倒数日按本机日历日期计算，不是定时闹钟。内容不上传 GitHub，也不提供云同步。</p>`:''}</div>`;
  const call=async(c:Record<string,unknown>)=>{try{changed(await bridge.deskTools!(c));}catch(e){toast((e as Error).message);}};
  el.querySelector<HTMLButtonElement>('[data-desk-toggle]')?.addEventListener('click',()=>void call({action:'visibility',visible:!data.visible}));el.querySelector<HTMLButtonElement>('[data-desk-hide]')?.addEventListener('click',()=>void call({action:'visibility',visible:false}));
  for(const [id,type] of [['note-form','note'],['date-form','countdown']]){const form=el.querySelector<HTMLFormElement>('#'+id);if(!form)continue;form.onsubmit=async e=>{e.preventDefault();const d=new FormData(form);try{const next=await bridge.deskTools!({action:type,id:String(d.get('id')||'')||undefined,title:String(d.get('title')||''),text:String(d.get('text')||''),date:String(d.get('date')||''),color:d.get('color'),pinned:d.has('pinned')});(document.activeElement as HTMLElement)?.blur();form.reset();changed(next);toast('已保存到本机');}catch(err){toast((err as Error).message);}};}
  const edit=(id:string,type:string)=>{const item=(type==='note'?data.notes:data.countdowns).find(n=>n.id===id)!;const form=el.querySelector<HTMLFormElement>(type==='note'?'#note-form':'#date-form')!;for(const [key,value] of Object.entries(item)){const input=form.elements.namedItem(key) as HTMLInputElement|null;if(input){if(input.type==='checkbox')input.checked=!!value;else input.value=String(value);}}form.scrollIntoView({block:'nearest'});(form.elements.namedItem('title') as HTMLInputElement).focus();};
  el.querySelectorAll<HTMLButtonElement>('[data-edit-note]').forEach(b=>b.onclick=()=>edit(b.dataset.editNote!,'note'));el.querySelectorAll<HTMLButtonElement>('[data-edit-date]').forEach(b=>b.onclick=()=>edit(b.dataset.editDate!,'countdown'));
  el.querySelectorAll<HTMLButtonElement>('[data-copy-note]').forEach(b=>b.onclick=()=>void call({action:'copy',id:b.dataset.copyNote}));
  el.querySelectorAll<HTMLButtonElement>('[data-remove-note]').forEach(b=>b.onclick=()=>void call({action:'remove',type:'note',id:b.dataset.removeNote}));el.querySelectorAll<HTMLButtonElement>('[data-remove-date]').forEach(b=>b.onclick=()=>void call({action:'remove',type:'countdown',id:b.dataset.removeDate}));
  el.querySelectorAll<HTMLButtonElement>('[data-skin-choice]').forEach(b=>b.onclick=()=>{if(b.dataset.skinChoice!=='garden'&&!active){document.querySelector<HTMLButtonElement>('[data-tab=account]')?.click();return;}void call({action:'skin',skin:b.dataset.skinChoice});});
}
