import presets from '../shared/weather-presets.json';
export interface Location { id: string; name: string; admin: string; country: string; latitude: number; longitude: number; timezone: string }
export type Kind = keyof typeof presets;
export interface Effects {rain:number;snow:number;hail:number;fog:number;dust:number;thunder:boolean;ice:boolean}
export interface Weather { locationId: string; fetchedAt: number; dataTime: number|null; provider: string; providerId?:string; dataType?:string; utcOffsetSeconds?:number; effects?:Effects; dayEstimated?:boolean; sourceNote?:string|null; fallback?:boolean; timezone: string; temperature: number; feelsLike: number | null; humidity: number | null; wind: number | null; windDirection: number | null; precipitation: number | null; cloudCover: number | null; isDay: boolean; code: number; kind: Kind; label: string; high: number | null; low: number | null; sunrise: number | null; sunset: number | null; hours: { time: number; temperature: number; precipitation: number | null; code: number }[] }
export interface Settings { onboardingComplete?:boolean; detail?:'classic'|'crafted';weatherNotifications?:boolean; location: Location | null; model: 'auto' | 'default' | 'landmark'; landmarkId?:string; weatherSource?:string; quality?:'economy'|'balanced'|'high'; size: number; fps: number; visible: boolean; locked: boolean; alwaysOnTop: boolean; paused: boolean; reducedMotion: boolean; pauseOnBattery: boolean; pauseOnFullscreen: boolean; showDetails: boolean; mode: 'widget' | 'wallpaper' }
export interface AirPoint { time:number; aqi:number|null; pm25:number|null; pm10:number|null }
export interface DeskTools {notes:{id:string;title:string;text:string;color:string;pinned:boolean}[];countdowns:{id:string;title:string;date:string;pinned:boolean}[];skin:string;visible:boolean}
export interface EnvironmentState { air:(AirPoint & {locationId:string;fetchedAt:number;provider:string;standard:string;hours:AirPoint[]})|null; loading:boolean; error:string|null; history:{weather:{time:number;temperature:number|null;humidity:number|null;wind:number|null;source:string}[];air:(AirPoint & {source:string})[]} }
export interface AppState { deskTools?:DeskTools; version?:string;sceneDetail?:'classic'|'crafted';activation?:{device:string;active:boolean;plan:string;expiresAt:number|null;status:string;message:string|null};updates?:{status:string;version:string;latest:string|null;percent:number;error:string|null;lastChecked:number|null};edition?:{purchaseUrl:string;trialDays:number;features:string[]};favorites?:Location[];insights?:{id:string;title:string;detail:string;level:string}[]; environment?:EnvironmentState; testMode?:boolean; settings: Settings; weather: Weather | null; sources?:{id:string;name:string;configured:boolean;state?:string;detail?:string;retryAt?:number}[]; credentialStatus?:{openweather:boolean;qweather:boolean;qweatherHost:string}; error: string | null; loading: boolean; availableLandmark: string | null; model: string; desktop: boolean; platform: string; autoStart: boolean; packaged: boolean; pauseReason: string | null }
export interface Bridge { deskTools?(command:Record<string,unknown>):Promise<AppState>; activate?(code:string):Promise<AppState>;favorite?(command:{action:string;id?:string}):Promise<AppState>; state(): Promise<AppState>; credentials(patch:Record<string,string|null>):Promise<AppState>; search(query: string): Promise<Location[]>; setLocation(location: Partial<Location>): Promise<AppState>; settings(patch: Partial<Settings>): Promise<AppState>; action(name: string): Promise<AppState>; subscribe(callback: (state: AppState) => void): () => void }
declare global { interface Window { qihou?: Bridge & {deskDrag?(phase:string):Promise<void>;drag?(phase:'start'|'move'|'end'):Promise<void>} } }
